### ISSUE TITLE
Move docs to gh-pages branch

### ISSUE THREAD

**Issue by ldesousa** [soilwise-he/soilwise-architecture#11]
Since the docs are auto-generated it would be better to have them in the gh-pages branch. This would simplify access (GitHub serves the HTML automatically) and also avoid inadvertent editions of the HTML in the main branch.

**Comment by DajanaSnopkova** [comment]
Thanks, I didn't know what is the best practice... I added /docs folder to the empty branch gh-pages and reverted the former commit in the main branch.

**Comment by pvgenuchten** [comment]
best practice is to have the markdown sources in main branch and render as html in the gh-pages branch.
