### ISSUE TITLE
connecton GUI to Ingestion?

### ISSUE THREAD

**Issue by boswol** [soilwise-he/soilwise-architecture#2]
A very small detail, I assume the GUI is not only linked to the "Manual data entry forms", but also the "Manual meta data entry forms".

![image](https://github.com/soilwise-he/soilwise-architecture/assets/66209693/b400dde8-e1de-4318-a53c-fdd129440d5a)

**Comment by DajanaSnopkova** [comment]
Fixed in [commit](https://github.com/soilwise-he/soilwise-architecture/commit/ace31cbf7e8c12016abc5d4f98b1db7df90e553d).
