### ISSUE TITLE
format of extracted data stored in Repository Storage?

### ISSUE THREAD

**Issue by boswol** [soilwise-he/soilwise-architecture#3]
How will the (meta)data of the "Ingestion" component be further stored in the "Repository Storage" component? From the scheme I assume as "source logs", however, I relate logs to logging/reporting of technical processes and not the actual data extracted during the technical process?

**Comment by pvgenuchten** [comment]
It's always good to keep a copy of the raw ingested content, for reproducability, the format is less relevant, so logging to stdout could be enough. After processing of the content a relevant augmented subset may be included on a queryable repository, such as git, database or graph/triple store.

**Comment by DajanaSnopkova** [comment]
I believe this is currently resolved in the new archi version (after Brugges meeting).
