### ISSUE TITLE
Sensor Server and Sensor Information?

### ISSUE THREAD

**Issue by boswol** [soilwise-he/soilwise-architecture#5]
In the grant agreement I find no mention of sensor information or data. What will these components do? Provide actual sensor data? I have always worked with sensor data as (quasi)real-time IoT data and as we are working with repositories I would think this will be difficult?

**Comment by pvgenuchten** [comment]
the iso28258 model for soil data is heavily inspired by Observations and measurements. Each field observation or lab analyses on a sample is modeled as an O&M observation on a (sample of a) soil horizon at a profile location.

Sensorthings API (and Sensor Observation Service) are the relevant exchange mechanisms to exchange sensor data.

**Comment by ldesousa** [comment]
@boswol Sensors do not feature directly in the old ISO-28258 domain model, and therefore I did not include it in the [ISRIC data model](https://git.wur.nl/isric/databases/iso28258-public). However, Sensors feature prominently in OMS (the follow up to O&M) and in SOSA (the Semantic Web version). 

Sensors will eventually feature in the GloSIS web ontology, perhaps this project provides the right venue for that.

**Comment by DajanaSnopkova** [comment]
For the first iteration Sensor components were now removed from the architecture design. I am closing this issue for the time being.
